name: Release
on:
  release:
    types: [published]

env:
  GITHUB_ACTION_TAG: ${{ github.ref_name }}

jobs:
  build-amd64-digest:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: "Read secrets"
      if: github.repository_owner == 'rancher'
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;

    # For forks, store docker credentials in GHA secrets
    - name: Build and push amd64 digest image 
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: hardened-traefik
        make-target: image-push-digest
        platforms: linux/amd64
        tag: ${{ github.event.release.tag_name }}
        public-repo: ${{ github.repository_owner }}
        public-username: ${{ github.repository_owner == 'rancher' && env.DOCKER_USERNAME || secrets.DOCKER_USERNAME }}
        public-password: ${{ github.repository_owner == 'rancher' && env.DOCKER_PASSWORD || secrets.DOCKER_PASSWORD }}
        
        push-to-prime: false

        # prime-repo: rancher
        # prime-registry: ${{ env.PRIME_REGISTRY }}
        # prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
        # prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}
        # push-to-prime: ${{ github.repository_owner == 'rancher' }}

    - name: Upload metadata files
      uses: actions/upload-artifact@v4
      with:
        name: metadata-amd64
        path: metadata-linux-amd64.json
        if-no-files-found: error
        retention-days: 1

  build-arm64-digest:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: "Read secrets"
      if: github.repository_owner == 'rancher'
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;

    # For forks, store docker credentials in GHA secrets
    - name: Build and push arm64 digest image 
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: hardened-traefik
        make-target: image-push-digest
        platforms: linux/arm64
        tag: ${{ github.event.release.tag_name }}
        public-repo: ${{ github.repository_owner }}
        public-username: ${{ github.repository_owner == 'rancher' && env.DOCKER_USERNAME || secrets.DOCKER_USERNAME }}
        public-password: ${{ github.repository_owner == 'rancher' && env.DOCKER_PASSWORD || secrets.DOCKER_PASSWORD }}
        
        push-to-prime: false

        # prime-repo: rancher
        # prime-registry: ${{ env.PRIME_REGISTRY }}
        # prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
        # prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}
        # push-to-prime: ${{ github.repository_owner == 'rancher' }}

    - name: Upload metadata files
      uses: actions/upload-artifact@v4
      with:
        name: metadata-arm64
        path: metadata-linux-arm64.json
        if-no-files-found: error
        retention-days: 1


  merge:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - build-amd64-digest
      - build-arm64-digest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download metadata files
        uses: actions/download-artifact@v4
        with:
          pattern: metadata-*
          merge-multiple: true

      - name: "Read secrets"
        if: github.repository_owner == 'rancher'
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;

      - name: Create manifest list and push
        id: push-manifest
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        with:
          make-target: manifest-push
          image: hardened-traefik
          tag: ${{ github.event.release.tag_name }}

          public-repo: ${{ github.repository_owner }}
          public-username: ${{ github.repository_owner == 'rancher' && env.DOCKER_USERNAME || secrets.DOCKER_USERNAME }}
          public-password: ${{ github.repository_owner == 'rancher' && env.DOCKER_PASSWORD || secrets.DOCKER_PASSWORD }}
          
          push-to-prime: false

          # prime-repo: rancher
          # prime-registry: ${{ env.PRIME_REGISTRY }}
          # prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
          # prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}
          # push-to-prime: ${{ github.repository_owner == 'rancher' }}

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ github.repository_owner }}/hardened-traefik:${{ github.event.release.tag_name }}